### ISSUE TITLE
关于上传过程中remove按钮的问题

### ISSUE THREAD

**Issue by SharmyMing** [AiursoftWeb/AiurDrive#11]
上传文件过程中点击此按钮并没有什么作用
![image](https://user-images.githubusercontent.com/33769737/119825400-7c01f700-bf29-11eb-804d-dc4cf9803b79.png)

**Comment by Anduin2017** [comment]
I gonna remove this button.

**Comment by Anduin2017** [comment]
Checked in. Now you can test it on staging.
