### ISSUE TITLE
Item of Action did not showed fully

### ISSUE THREAD

**Issue by aimerneige** [AiursoftWeb/AiurDrive#18]
![image](https://user-images.githubusercontent.com/51701792/175607573-58ce1d07-3f6e-4b2f-b490-e8165890ffe1.png)

**Comment by Anduin2017** [comment]
PR welcome

**Comment by fissssssh** [comment]
#17 @Anduin2017 should fixed.

**Comment by Anduin2017** [comment]
Thank you @fissssssh !!!
