### ISSUE TITLE
关于 Unicode 导致的严重漏洞

### ISSUE THREAD

**Issue by Perlistan** [AiursoftWeb/AiurDrive#4]
如果用【U+2029、U+2028】创建无后缀文件会导致上传到 driver 后无法删除，现在我的资源文件夹已被垃圾文件占位污染

**Comment by Perlistan** [comment]
同时也无法打开下载链接和预览

**Comment by Anduin2017** [comment]
看来，现在你只能先靠删site再重建site来重置你的site了……能把这种垃圾文件发过来一份吗？

谢谢

**Comment by Anduin2017** [comment]
Will be released in production soon.
